run:
	python3 src/main.py

all:
	cp config/all.json config/config.json && make run

piscine:
	cp config/piscine.json config/config.json && make run

sql:
	cp config/sql.json config/config.json && make run

miniproject:
	cp config/ING_PREPAS.json config/config.json && make run

42sh:
	cp config/42sh.json config/config.json && make run

base:
	cp config/base_configs.json config/config.json && make run